version: "3.2"
services:
  frontend:
    image: ccanasj/teerece:frontend
    container_name: trc-frontend
    ports:
      - 80:80
    restart: always
  
  backend:
    image: ccanasj/teerece:backend
    container_name: trc-backend
    ports:
    - 5000:5000
    restart: always
    environment:
        NODE_ENV: production
        PORT: 5000
        HOST: 0.0.0.0
