version: "3.2"
services:
  frontend:
    image: ccanasj/teerece:frontend
    ports:
    - 3000:80
    expose:
    - "3000"
    restart: always
  
  backend:
    image: ccanasj/teerece:backend
    ports:
    - 5000:5000
    expose:
    - "5000"
    restart: always
    environment:
        NODE_ENV: production
        PORT: 5000
        HOST: 0.0.0.0
