version: "3.2"
services:
  front:
    image: robacion_frontend:1.0.1
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
    - 80:80
    expose:
    - "80"
    restart: always
    environment:
        NODE_ENV: production
        PORT: 80
        HOST: 0.0.0.0
  backend:
    image: robacion_backend:1.0.1
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
    - 5000:5000
    expose:
    - "5000"
    restart: always
    environment:
        NODE_ENV: production
        PORT: 5000
        HOST: 0.0.0.0