version: "3.2"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600 trc-frontend trc-backend
    depends_on:
      - frontend
      - backend
  frontend:
    image: ccanasj/teerece:frontend
    container_name: trc-frontend
    ports:
      - 80:80
    restart: always
  
  backend:
    image: ccanasj/teerece:backend
    container_name: trc-backend
    ports:
    - 5000:5000
    restart: always
    environment:
        NODE_ENV: production
        PORT: 5000
        HOST: 0.0.0.0
        ELASTIC_APM_SERVICE_NAME : "TRC Api"
        ELASTIC_APM_SECRET_TOKEN : "Token"
        ELASTIC_APM_SERVER_URL : http://APMSERVER:8200/